// lang-terms.js (robustan za terms.html; radi i ako dodaš -en sufikse)
let trenutniJezik = localStorage.getItem('forecastlerLang') || 'en';

const translations = {
  en: {
    headerLinks: { home: "Home", about: "About Us", contact: "Contact", blog: "Blog" },
    footerLinks: { disclaimer:"Disclaimer", terms:"Terms of Use", privacy:"Privacy Policy", cookies:"Cookie Policy", sitemap:"Sitemap", faq:"FAQ" },

    meta: {
      title: "Terms of Use",
      effective: "Effective Date: 17 June 2025",
      updated:  "Last Updated: 15 August 2025",
      intro: "These Terms of Use (“Terms”) govern your access to and use of the Forecastler platform (the “Platform”, “we”, “us”, “our”). By using the Platform, you confirm that you have read and accepted these Terms together with our Privacy Policy, Cookies Policy, and Disclaimer. If you do not agree, please do not use the Platform."
    },

    s1: {
      title: "1) Who may use the Platform (eligibility)",
      p1: "The Platform may be used worldwide, except where prohibited by local law.",
      p2: "Individuals under 13 may not use the Platform. Individuals aged 13–18 may use the Platform with parental/guardian consent and supervision."
    },

    s2: {
      title: "2) Service description and how to use it",
      def: "<strong>Definitions.</strong> “Input” means anything you submit (e.g., a subject description/question). “AI Output” means the answer/assessment generated by the system. A “Subject” is the person, object, event, or situation you ask about. “Opt-out” is a verifiable request by a Subject that no forecasts be generated about them.",
      p1: "In the first field you enter a Subject description; in the second field you ask a future-oriented YES/NO question.",
      p2: "The system returns a YES/NO answer and a probability percentage.",
      p3: "No registration or login is required.",
      p4: "The Platform works in multiple languages; quality may vary by language and input quality.",
      p5: "You can create “chips” (shortcuts) for Subjects: data are stored via localStorage on your device; clicking a chip reloads the description. These data are not visible to other users and are not stored on our servers.",
      p6: "More detailed descriptions may yield more informative answers (no accuracy guarantee)."
    },

    s3: {
      title: "3) Question rules",
      p1: "Questions must be about the future and framed so they can be answered YES/NO.",
      p2: "We do not respond to questions that are: (a) unclear/ambiguous, (b) not YES/NO, (c) not about the future, or (d) contrary to these Terms or applicable law.",
      p3: "We may limit/decline/interrupt answer generation at our reasonable discretion (e.g., abuse, technical issues)."
    },

    s4: {
      title: "4) Limitations and technical notes",
      p1: "<strong>Availability.</strong> The service is provided “as is” and “as available”; outages, delays, errors, maintenance, and functional changes may occur.",
      p2: "<strong>Languages.</strong> We support multiple languages; accuracy and style may vary. In doubtful cases we recommend English.",
      p3: "<strong>System limits.</strong> We may apply rate limits, input size limits, and context-length limits.",
      p4: "<strong>localStorage.</strong> Data on your device can be lost if you clear browser data, change devices, or use cleaning tools; we cannot restore them.",
      p5: "<strong>No account.</strong> Because registration is not enabled, features such as cross-device sync are not available.",
      p6: "<strong>Security &amp; compatibility.</strong> We apply reasonable measures, but no system is 100% secure; we do not guarantee compatibility with all devices/browsers/extensions/plugins. Third parties (e.g., hosting/CDN) can affect performance."
    },

    s5: {
      title: "5) Nature of answers &amp; no professional advice",
      p1: "AI answers and probability estimates are informational and not legal, financial, medical, safety, tax, or any other professional advice.",
      p2: "We do not guarantee accuracy, completeness, timeliness, or fitness for your situation; you rely at your own risk.",
      p3: "For consequential decisions consult a qualified professional; in emergencies contact the relevant authorities.",
      p4: "See the Disclaimer for details."
    },

    s6: {
      title: "6) Your inputs and privacy",
      p1: "Descriptions and questions you submit are processed by our service to generate answers; by default they are not public and not visible to other users.",
      p2: "Data in localStorage remain on your device (except content you submit for generating an answer).",
      p3: "Personal data processing is governed by our Privacy Policy (retention periods, your rights).",
      p4: "Do not submit sensitive data unless necessary; do not submit third-party personal data without a legal basis."
    },

    s7: {
      title: "7) Prohibited uses",
      lead: "Prohibited, among other things:",
      p1: "Violations of law and third-party rights (privacy, copyright/trademark, trade secrets, reputation), and publishing defamatory, offensive, threatening, discriminatory, or hate-speech content.",
      p2: "Unauthorized copying and distribution of Platform content, including UI/design/layout, texts and databases, AI Outputs and metadata, guides and documents; data-mining/scraping or building datasets/models without written consent or another legal basis.",
      p3: "Unauthorized screenshots and screen recording/streaming and public sharing of reproductions of the Platform or AI Outputs, except strictly personal, non-commercial use without publishing/sharing.",
      p4: "Subject opt-out. If a Subject verifiably requests a ban on forecasts about them, you must not submit new queries about that Subject. We may implement blocklists and remove publicly shared content that violates the ban.",
      p5: "Public display/promotion of results about third parties (individuals, institutions, organizations, companies, nations, systems) without their authorization or another legal basis, including marketing/PR/sponsored posts.",
      p6: "Abuse and security incidents (malicious code, circumvention of measures, DDoS, large-scale automated queries without approval, reverse engineering, unauthorized indexing, load testing without consent).",
      p7: "Disinformation and manipulation (intentional misinterpretation of AI Outputs, fabricated claims, doxxing, incitement to harassment).",
      p8: "Improper inputs (third-party personal data without basis, confidential information, content you have no right to disclose).",
      p9: "Circumventing usage restrictions (e.g., via VPN/proxy) when contrary to law or these Terms."
    },

    s8: {
      title: "8) Intellectual property and licenses",
      p1: "<strong>Our content.</strong> All rights in the software, design, text, logos, and other Platform elements belong to us or our licensors. You acquire no rights other than a limited right to use the Platform under these Terms.",
      p2: "<strong>Your Input.</strong> You grant us a non-exclusive, transferable, royalty-free, worldwide license to use your Input to: (a) provide and improve the service, and (b) for security/diagnostic purposes, in line with the Privacy Policy.",
      p3: "<strong>AI Output.</strong> You may use AI Outputs for personal and/or business purposes, subject to third-party rights and applicable law. AI Outputs may be similar to outputs generated for other users.",
      p4: "<strong>Public sharing of AI Outputs.</strong> Unless expressly permitted by these Terms or our written consent, public disclosure, redistribution, or commercial exploitation of AI Outputs/reports that contain identifiable references to third parties is prohibited without their authorization or another legal basis.",
      p5: "<strong>Screenshots and interface recordings.</strong> These are treated as derivative works and are subject to these Terms; permitted only for personal, non-commercial use without public sharing, unless otherwise pre-approved by the Forecastler team.",
      p6: "<strong>Datasets and models.</strong> Using Platform content/AI Outputs to train or evaluate machine-learning models is prohibited without written consent."
    },

    s9: { title: "9) Third-party links and services", p1: "We may include links to external sites/services. We do not control or guarantee their content, security, or policies; use them at your own risk." },

    s10: {
      title: "10) Suspension and termination",
      p1: "We may temporarily or permanently restrict access to the Platform, in whole or in part, if: (a) you violate these Terms or law, (b) there is a security risk, or (c) technical/legal reasons require it.",
      p2: "You may stop using the service at any time. You delete localStorage data via your browser settings.",
      p3: "If Sections 7 and/or 8 are violated, we may: (a) remove disputed content, (b) apply technical restrictions (blocklists, IP blocks), (c) send takedown requests to third-party platforms, and (d) pursue legal action and seek damages.",
      p4: "For a valid opt-out request (Section 7.4), we may disable new targeted forecasts and remove publicly shared materials that violate the ban, to the extent technically and legally feasible."
    },

    s11: { title: "11) Disclaimer of warranties", p1: "To the maximum extent permitted by law, the service is provided “as is” and “as available”, without any express or implied warranties (including accuracy, fitness for a particular purpose, continuity, or error-free operation)." },

    s12: {
      title: "12) Limitation of liability",
      p1: "To the maximum extent permitted by law, we and our partners are not liable for indirect, incidental, special, consequential, or punitive damages, or for loss of profits, data, or reputation arising from or related to the use or inability to use the Platform.",
      p2: "Where liability cannot be excluded, it is limited to the amount you may have paid to us in the six (6) months prior to the event (if applicable).",
      p3: "Nothing herein limits liability for willful misconduct or gross negligence, or mandatory consumer rights."
    },

    s13: { title: "13) Indemnification", p1: "You agree to indemnify and hold us harmless from third-party claims, damages, and costs (including reasonable attorneys’ fees) arising from: (a) your breach of these Terms or law, (b) infringement of third-party rights, or (c) misuse of the Platform." },

    s14: { title: "14) Changes to the service and these Terms", p1: "We may update the Platform and/or these Terms. Changes take effect when posted on this page with an updated “Last Updated” date. Your continued use constitutes acceptance." },

    s15: { title: "15) Governing law and jurisdiction", p1: "These Terms are governed by the laws of the Republic of Serbia (unless mandatory rules of your residence provide otherwise). The court of Subotica has subject-matter and local jurisdiction, unless otherwise mandatorily required by law." },

    s16: {
      title: "16) Communications and notices (notice &amp; action)",
      lead: "Report violations (defamation, copyright/trademark, unlawful content) to forecastlerteam@gmail.com with:",
      p1: "• a description and location (URL/screenshot),",
      p2: "• the legal basis for your claim,",
      p3: "• your contact details and a truthfulness statement.",
      foot: "We may temporarily restrict/remove disputed content during review, request additional information, and act within a reasonable time consistent with applicable law."
    },

    s17: { title: "17) Language versions", p1: "The Platform is available in multiple languages. In case of inconsistency, the English version prevails, unless local law provides otherwise." },

    s18: {
      title: "18) Miscellaneous",
      p1: "<strong>Severability.</strong> If any provision is invalid, the remainder stays in force; the invalid provision is replaced with a valid one most closely reflecting the intent.",
      p2: "<strong>Assignment.</strong> You may assign rights/obligations only with our written consent; we may assign to affiliates as part of business changes.",
      p3: "<strong>Force majeure.</strong> We are not liable for delays/non-performance due to events beyond our reasonable control.",
      p4: "<strong>Entire agreement.</strong> These Terms, the Privacy Policy, Cookies Policy, and the Disclaimer constitute the entire agreement regarding the Platform.",
      p5: "<strong>No waiver.</strong> Failure to enforce a right does not constitute a waiver."
    },

    s19: { title: "19) Contact", p1: "Forecastler Team", p2: "Email: forecastlerteam@gmail.com" }
  },

  sr: {
    headerLinks: { home: "Početna", about: "O nama", contact: "Kontakt", blog: "Blog" },
    footerLinks: { disclaimer:"Odricanje od odgovornosti", terms:"Uslovi korišćenja", privacy:"Politika privatnosti", cookies:"Politika kolačića", sitemap:"Mapa sajta", faq:"FAQ" },

    meta: {
      title: "Uslovi korišćenja",
      effective: "Datum stupanja na snagu: 17. jun 2025.",
      updated:  "Poslednje ažuriranje: 15. avgust 2025.",
      intro: "Ovi Uslovi korišćenja („Uslovi“) uređuju pristup i korišćenje platforme Forecastler („Platforma“, „mi“, „nas“, „naše“). Korišćenjem Platforme potvrđujete da ste pročitali i prihvatili ove Uslove zajedno sa Politikom privatnosti, Politikom kolačića i Odricanjem od odgovornosti. Ako se ne slažete, molimo vas da ne koristite Platformu."
    },

    s1: {
      title: "1) Ko može da koristi Platformu (uslovi podobnosti)",
      p1: "Platforma se može koristiti širom sveta, osim gde je to zabranjeno lokalnim pravom.",
      p2: "Lica mlađa od 13 godina ne mogu koristiti Platformu. Lica uzrasta 13–18 godina mogu je koristiti uz saglasnost i nadzor roditelja/staratelja."
    },

    s2: {
      title: "2) Opis usluge i kako se koristi",
      def: "<strong>Definicije.</strong> „Ulaz“ (Input) predstavlja sve što unesete (npr. opis subjekta/pitanje). „AI izlaz“ (AI Output) je odgovor/procena koju sistem generiše. „Subjekt“ je osoba, objekat, događaj ili situacija o kojoj pitate. „Opt-out“ je proverljiv zahtev Subjekta da se o njemu ne generišu prognoze.",
      p1: "U prvo polje unosite opis Subjekta; u drugo postavljate pitanje o budućnosti na koje se odgovara DA/NE.",
      p2: "Sistem vraća odgovor DA/NE i procenat verovatnoće.",
      p3: "Registracija i prijava nisu potrebne.",
      p4: "Platforma radi na više jezika; kvalitet može varirati u zavisnosti od jezika i kvaliteta unosa.",
      p5: "Možete praviti „čipove“ (prečice) za Subjekte: podaci se čuvaju preko localStorage na vašem uređaju; klik na čip ponovo učitava opis. Ovi podaci nisu vidljivi drugim korisnicima i ne čuvaju se na našim serverima.",
      p6: "Detaljniji opisi mogu dati informativnije odgovore (bez garancije tačnosti)."
    },

    s3: {
      title: "3) Pravila za pitanja",
      p1: "Pitanja moraju biti o budućnosti i formulisana tako da se može odgovoriti DA/NE.",
      p2: "Ne odgovaramo na pitanja koja su: (a) nejasna/dvosmislena, (b) nisu DA/NE, (c) nisu o budućnosti ili (d) su protivna ovim Uslovima ili važećem pravu.",
      p3: "Možemo ograničiti/odbitI/prekinuti generisanje odgovora po razumnom nahođenju (npr. zloupotreba, tehnički problemi)."
    },

    s4: {
      title: "4) Ograničenja i tehničke napomene",
      p1: "<strong>Dostupnost.</strong> Usluga se pruža „takva kakva je“ i „u zavisnosti od dostupnosti“; mogući su prekidi, kašnjenja, greške, održavanje i funkcionalne izmene.",
      p2: "<strong>Jezici.</strong> Podržavamo više jezika; tačnost i stil mogu varirati. U sumnjivim slučajevima preporučujemo engleski.",
      p3: "<strong>Sistemska ograničenja.</strong> Možemo primenjivati ograničenja brzine, veličine unosa i dužine konteksta.",
      p4: "<strong>localStorage.</strong> Podaci na uređaju mogu biti izgubljeni brisanjem istorije/keša, promenom uređaja ili korišćenjem alata za čišćenje; ne možemo ih povratiti.",
      p5: "<strong>Bez naloga.</strong> Pošto registracija nije omogućena, funkcije poput sinhronizacije između uređaja nisu dostupne.",
      p6: "<strong>Bezbednost i kompatibilnost.</strong> Primenujemo razumne mere, ali nijedan sistem nije 100% bezbedan; ne garantujemo kompatibilnost sa svim uređajima/pregledačima/ekstenzijama/dodacima. Treće strane (npr. hosting/CDN) mogu uticati na performanse."
    },

    s5: {
      title: "5) Priroda odgovora i nepostojanje profesionalnog saveta",
      p1: "AI odgovori i procene verovatnoće su informativni i ne predstavljaju pravni, finansijski, medicinski, bezbednosni, poreski niti bilo koji drugi profesionalni savet.",
      p2: "Ne garantujemo tačnost, potpunost, blagovremenost niti podobnost za vašu situaciju; oslanjate se na sopstveni rizik.",
      p3: "Za odluke sa posledicama konsultujte kvalifikovanog stručnjaka; u hitnim slučajevima obratite se nadležnim službama.",
      p4: "Detalje videti u Odricanju od odgovornosti."
    },

    s6: {
      title: "6) Vaši unosi i privatnost",
      p1: "Opisi i pitanja koja pošaljete obrađuju se radi generisanja odgovora; podrazumevano nisu javni i nisu vidljivi drugim korisnicima.",
      p2: "Podaci u localStorage ostaju na vašem uređaju (izuzev sadržaja koji šaljete za generisanje odgovora).",
      p3: "Obrada ličnih podataka uređena je Politikom privatnosti (rokovi čuvanja, vaša prava).",
      p4: "Ne unosite osetljive podatke osim ako je neophodno; ne unosite lične podatke trećih lica bez pravnog osnova."
    },

    s7: {
      title: "7) Zabranjene upotrebe",
      lead: "Zabranjeno je, između ostalog:",
      p1: "Kršenje zakona i prava trećih lica (privatnost, autorsko/žig, poslovne tajne, ugled) i objavljivanje klevetničkog, uvredljivog, pretećeg, diskriminatornog ili govora mržnje.",
      p2: "Neovlašćeno kopiranje i distribucija sadržaja Platforme, uključujući UI/dizajn/raspored, tekstove i baze podataka, AI izlaze i metapodatke, vodiče i dokumenta; data-mining/scraping ili izgradnja skupova podataka/modela bez pismene saglasnosti ili drugog pravnog osnova.",
      p3: "Neovlašćeni skrinšotovi i snimanje/prenos interfejsa i javno deljenje reprodukcija Platforme ili AI izlaza, osim strogo lične, nekomercijalne upotrebe bez objavljivanja/deljenja.",
      p4: "Opt-out Subjekta. Ako Subjekt proverljivo zatraži zabranu prognoza o njemu, ne smete slati nova pitanja o tom Subjektu. Možemo primeniti blok-liste i ukloniti javno podeljen sadržaj koji krši zabranu.",
      p5: "Javno prikazivanje/promocija rezultata o trećim licima (pojedincima, institucijama, organizacijama, kompanijama, nacijama, sistemima) bez njihove dozvole ili drugog pravnog osnova, uključujući marketing/PR/sponzorisane objave.",
      p6: "Zloupotrebe i bezbednosni incidenti (maliciozni kod, zaobilaženje mera, DDoS, masovni automatizovani upiti bez odobrenja, reverzni inženjering, neovlašćeno indeksiranje, opterećujući testovi bez saglasnosti).",
      p7: "Dezinformacije i manipulacije (namerno pogrešno tumačenje AI izlaza, izmišljene tvrdnje, doxxing, podsticanje na uznemiravanje).",
      p8: "Neprimereni unosi (lični podaci trećih lica bez osnova, poverljive informacije, sadržaj koji nemate pravo da otkrivate).",
      p9: "Zaobilaženje ograničenja korišćenja (npr. putem VPN/proxy) kada je suprotno zakonu ili ovim Uslovima."
    },

    s8: {
      title: "8) Intelektualna svojina i licence",
      p1: "<strong>Naš sadržaj.</strong> Sva prava na softver, dizajn, tekst, logotipe i druge elemente Platforme pripadaju nama ili našim davaocima licenci. Ne stičete prava osim ograničenog prava korišćenja u skladu sa ovim Uslovima.",
      p2: "<strong>Vaš Ulaz.</strong> Dajete nam neekskluzivnu, prenosivu, besplatnu, svetsku licencu da koristimo vaš Ulaz radi: (a) pružanja i unapređenja usluge i (b) bezbednosno-dijagnostičkih svrha, u skladu sa Politikom privatnosti.",
      p3: "<strong>AI izlaz.</strong> Možete koristiti AI izlaze u lične i/ili poslovne svrhe, uz poštovanje prava trećih lica i važećeg prava. AI izlazi mogu biti slični onima generisanim za druge korisnike.",
      p4: "<strong>Javno deljenje AI izlaza.</strong> Osim ako je izričito dozvoljeno ovim Uslovima ili našom pismenom saglasnošću, javno objavljivanje, redistribucija ili komercijalna eksploatacija AI izlaza/izveštaja sa prepoznatljivim referencama na treća lica je zabranjena bez njihove dozvole ili drugog pravnog osnova.",
      p5: "<strong>Skrinšotovi i snimci interfejsa.</strong> Tretiraju se kao izvedena dela i podležu ovim Uslovima; dozvoljeni su samo za ličnu, nekomercijalnu upotrebu bez javnog deljenja, osim ako Forecastler tim ne odobri drukčije.",
      p6: "<strong>Skupovi podataka i modeli.</strong> Korišćenje sadržaja/AI izlaza Platforme za obučavanje ili evaluaciju modela mašinskog učenja zabranjeno je bez pismene saglasnosti."
    },

    s9: { title: "9) Linkovi i usluge trećih strana", p1: "Možemo uključiti linkove ka spoljnim sajtovima/uslugama. Ne kontrolišemo niti garantujemo njihov sadržaj, bezbednost ili politike; koristite ih na sopstveni rizik." },

    s10: {
      title: "10) Obustava i prestanak korišćenja",
      p1: "Možemo privremeno ili trajno ograničiti pristup Platformi, u celosti ili delimično, ako: (a) kršite ove Uslove ili zakon, (b) postoji bezbednosni rizik ili (c) to zahtevaju tehnički/pravni razlozi.",
      p2: "Korišćenje možete prekinuti u bilo kom trenutku. Podatke iz localStorage brišete u podešavanjima pregledača.",
      p3: "Ako su povređeni odeljci 7 i/ili 8, možemo: (a) ukloniti sporni sadržaj, (b) primeniti tehnička ograničenja (blok-liste, IP blokade), (c) uputiti zahteve za uklanjanje trećim platformama i (d) preduzeti pravne radnje i potraživati štetu.",
      p4: "Za valjan opt-out zahtev (odeljak 7.4) možemo onemogućiti nove ciljane prognoze i ukloniti javno podeljene materijale koji krše zabranu, koliko je tehnički i pravno izvodljivo."
    },

    s11: { title: "11) Odricanje od garancija", p1: "U najvećoj meri dozvoljenoj zakonom, usluga se pruža „takva kakva je“ i „u zavisnosti od dostupnosti“, bez ikakvih izričitih ili prećutnih garancija (uključujući tačnost, pogodnost za određenu svrhu, kontinuitet rada ili rad bez grešaka)." },

    s12: {
      title: "12) Ograničenje odgovornosti",
      p1: "U najvećoj meri dozvoljenoj zakonom, mi i naši partneri ne odgovaramo za indirektnu, slučajnu, posebnu, posledičnu ili kaznenu štetu, niti za gubitak profita, podataka ili ugleda nastao usled ili u vezi sa korišćenjem ili nemogućnošću korišćenja Platforme.",
      p2: "Gde odgovornost ne može biti isključena, ograničena je na iznos koji ste eventualno platili u šest (6) meseci pre događaja (ako je primenljivo).",
      p3: "Ništa ovde ne ograničava odgovornost za nameru ili grubu nepažnju, niti obavezna prava potrošača."
    },

    s13: { title: "13) Naknada štete (indemnizacija)", p1: "Slažete se da nas obeštetite i zaštitite od potraživanja trećih lica, štete i troškova (uključujući razumne troškove advokata) nastalih zbog: (a) vašeg kršenja ovih Uslova ili zakona, (b) povrede prava trećih lica ili (c) zloupotrebe Platforme." },

    s14: { title: "14) Izmene usluge i ovih Uslova", p1: "Platformu i/ili ove Uslove možemo ažurirati. Izmene važe od objave na ovoj stranici uz ažurirani datum „Poslednje ažuriranje“. Nastavkom korišćenja prihvatate izmene." },

    s15: { title: "15) Merodavno pravo i nadležnost", p1: "Na ove Uslove primenjuje se pravo Republike Srbije (osim ako obavezna pravila vašeg prebivališta ne propisuju drugačije). Za sporove je nadležan sud u Subotici, osim ako je drukčije obavezno propisano." },

    s16: {
      title: "16) Komunikacija i obaveštenja (notice &amp; action)",
      lead: "Prijavite povrede (kleveta, autorsko/žig, nezakonit sadržaj) na forecastlerteam@gmail.com uz:",
      p1: "• opis i lokaciju sadržaja (URL/skrinšot),",
      p2: "• pravni osnov vašeg zahteva,",
      p3: "• vaše kontakt podatke i izjavu o istinitosti navoda.",
      foot: "Tokom razmatranja možemo privremeno ograničiti/ukloniti sporni sadržaj, zatražiti dodatne informacije i postupiti u razumnom roku u skladu sa važećim pravom."
    },

    s17: { title: "17) Jezičke verzije", p1: "Platforma je dostupna na više jezika. U slučaju neslaganja, prednost ima verzija na engleskom, osim ako lokalni propisi ne nalažu drugačije." },

    s18: {
      title: "18) Ostalo",
      p1: "<strong>Deljivost odredbi.</strong> Ako je neka odredba nevažeća, ostatak ostaje na snazi; nevažeća se zamenjuje važećom koja najviše odražava nameru.",
      p2: "<strong>Ustupanje.</strong> Prava/obaveze možete ustupiti samo uz našu pismenu saglasnost; mi možemo ustupiti povezanim licima u okviru poslovnih promena.",
      p3: "<strong>Viša sila.</strong> Ne odgovaramo za kašnjenja/nemogućnost izvršenja zbog događaja van naše razumne kontrole.",
      p4: "<strong>Celokupan ugovor.</strong> Ovi Uslovi, Politika privatnosti, Politika kolačića i Odricanje od odgovornosti čine celokupan sporazum u vezi sa Platformom.",
      p5: "<strong>Neodricanje.</strong> Propust u ostvarivanju prava ne predstavlja odricanje od tog prava."
    },

    s19: { title: "19) Kontakt", p1: "Forecastler tim", p2: "Imejl: forecastlerteam@gmail.com" }
  }
};

// Helperi: pokušaj bez sufiksa, pa sa "-en"
function byId(id){ return document.getElementById(id) || document.getElementById(id + "-en"); }
function setTxtAny(id, txt){ const el = byId(id); if (el && typeof txt === "string") el.textContent = txt; }
function setHTMLAny(id, html){ const el = byId(id); if (el && typeof html === "string") el.innerHTML = html; }

function setLanguage(lang) {
  const t = translations[lang] || translations.en;
  localStorage.setItem('forecastlerLang', lang);
  trenutniJezik = lang;

  // Header (desktop + mobile)
  if (t.headerLinks){
    setTxtAny("nav-home", t.headerLinks.home);
    setTxtAny("nav-about", t.headerLinks.about);
    setTxtAny("nav-contact", t.headerLinks.contact);
    setTxtAny("nav-blog", t.headerLinks.blog);

    setTxtAny("mnav-home", t.headerLinks.home);
    setTxtAny("mnav-about", t.headerLinks.about);
    setTxtAny("mnav-contact", t.headerLinks.contact);
    setTxtAny("mnav-blog", t.headerLinks.blog);
  }

  // Meta
  setTxtAny ("terms-title",  t.meta.title);
  setTxtAny ("terms-meta-1", t.meta.effective);
  setTxtAny ("terms-meta-2", t.meta.updated);
  setTxtAny ("terms-intro",  t.meta.intro);

  // S1
  setTxtAny("terms-s1-title", t.s1.title);
  setTxtAny("terms-s1-1",     t.s1.p1);
  setTxtAny("terms-s1-2",     t.s1.p2);

  // S2
  setTxtAny   ("terms-s2-title", t.s2.title);
  setHTMLAny  ("terms-s2-def",   t.s2.def);
  setTxtAny   ("terms-s2-1",     t.s2.p1);
  setTxtAny   ("terms-s2-2",     t.s2.p2);
  setTxtAny   ("terms-s2-3",     t.s2.p3);
  setTxtAny   ("terms-s2-4",     t.s2.p4);
  setTxtAny   ("terms-s2-5",     t.s2.p5);
  setTxtAny   ("terms-s2-6",     t.s2.p6);

  // S3
  setTxtAny("terms-s3-title", t.s3.title);
  setTxtAny("terms-s3-1",     t.s3.p1);
  setTxtAny("terms-s3-2",     t.s3.p2);
  setTxtAny("terms-s3-3",     t.s3.p3);

  // S4 (ima <strong>)
  setTxtAny  ("terms-s4-title", t.s4.title);
  setHTMLAny ("terms-s4-1",     t.s4.p1);
  setHTMLAny ("terms-s4-2",     t.s4.p2);
  setHTMLAny ("terms-s4-3",     t.s4.p3);
  setHTMLAny ("terms-s4-4",     t.s4.p4);
  setHTMLAny ("terms-s4-5",     t.s4.p5);
  setHTMLAny ("terms-s4-6",     t.s4.p6);

  // S5
  setTxtAny("terms-s5-title", t.s5.title);
  setTxtAny("terms-s5-1",     t.s5.p1);
  setTxtAny("terms-s5-2",     t.s5.p2);
  setTxtAny("terms-s5-3",     t.s5.p3);
  setTxtAny("terms-s5-4",     t.s5.p4);

  // S6
  setTxtAny("terms-s6-title", t.s6.title);
  setTxtAny("terms-s6-1",     t.s6.p1);
  setTxtAny("terms-s6-2",     t.s6.p2);
  setTxtAny("terms-s6-3",     t.s6.p3);
  setTxtAny("terms-s6-4",     t.s6.p4);

  // S7
  setTxtAny("terms-s7-title", t.s7.title);
  setTxtAny("terms-s7-lead",  t.s7.lead);
  setTxtAny("terms-s7-1",     t.s7.p1);
  setTxtAny("terms-s7-2",     t.s7.p2);
  setTxtAny("terms-s7-3",     t.s7.p3);
  setTxtAny("terms-s7-4",     t.s7.p4);
  setTxtAny("terms-s7-5",     t.s7.p5);
  setTxtAny("terms-s7-6",     t.s7.p6);
  setTxtAny("terms-s7-7",     t.s7.p7);
  setTxtAny("terms-s7-8",     t.s7.p8);
  setTxtAny("terms-s7-9",     t.s7.p9);

  // S8 (ima <strong>)
  setTxtAny  ("terms-s8-title", t.s8.title);
  setHTMLAny ("terms-s8-1",     t.s8.p1);
  setHTMLAny ("terms-s8-2",     t.s8.p2);
  setHTMLAny ("terms-s8-3",     t.s8.p3);
  setHTMLAny ("terms-s8-4",     t.s8.p4);
  setHTMLAny ("terms-s8-5",     t.s8.p5);
  setHTMLAny ("terms-s8-6",     t.s8.p6);

  // S9
  setTxtAny("terms-s9-title", t.s9.title);
  setTxtAny("terms-s9-1",     t.s9.p1);

  // S10
  setTxtAny("terms-s10-title", t.s10.title);
  setTxtAny("terms-s10-1",     t.s10.p1);
  setTxtAny("terms-s10-2",     t.s10.p2);
  setTxtAny("terms-s10-3",     t.s10.p3);
  setTxtAny("terms-s10-4",     t.s10.p4);

  // S11
  setTxtAny("terms-s11-title", t.s11.title);
  setTxtAny("terms-s11-1",     t.s11.p1);

  // S12
  setTxtAny("terms-s12-title", t.s12.title);
  setTxtAny("terms-s12-1",     t.s12.p1);
  setTxtAny("terms-s12-2",     t.s12.p2);
  setTxtAny("terms-s12-3",     t.s12.p3);

  // S13
  setTxtAny("terms-s13-title", t.s13.title);
  setTxtAny("terms-s13-1",     t.s13.p1);

  // S14
  setTxtAny("terms-s14-title", t.s14.title);
  setTxtAny("terms-s14-1",     t.s14.p1);

  // S15
  setTxtAny("terms-s15-title", t.s15.title);
  setTxtAny("terms-s15-1",     t.s15.p1);

  // S16 (lead + foot)
  setTxtAny ("terms-s16-title", t.s16.title);
  setTxtAny ("terms-s16-lead",  t.s16.lead);
  setTxtAny ("terms-s16-1",     t.s16.p1);
  setTxtAny ("terms-s16-2",     t.s16.p2);
  setTxtAny ("terms-s16-3",     t.s16.p3);
  setTxtAny ("terms-s16-foot",  t.s16.foot);

  // S17
  setTxtAny("terms-s17-title", t.s17.title);
  setTxtAny("terms-s17-1",     t.s17.p1);

  // S18 (ima <strong>)
  setTxtAny  ("terms-s18-title", t.s18.title);
  setHTMLAny ("terms-s18-1",     t.s18.p1);
  setHTMLAny ("terms-s18-2",     t.s18.p2);
  setHTMLAny ("terms-s18-3",     t.s18.p3);
  setHTMLAny ("terms-s18-4",     t.s18.p4);
  setHTMLAny ("terms-s18-5",     t.s18.p5);

  // S19
  setTxtAny("terms-s19-title", t.s19.title);
  setTxtAny("terms-s19-1",     t.s19.p1);
  setTxtAny("terms-s19-2",     t.s19.p2);

  // Footer
  if (t.footerLinks){
    setTxtAny("link-disclaimer", t.footerLinks.disclaimer);
    setTxtAny("link-terms",      t.footerLinks.terms);
    setTxtAny("link-privacy",    t.footerLinks.privacy);
    setTxtAny("link-cookies",    t.footerLinks.cookies);
    setTxtAny("link-sitemap",    t.footerLinks.sitemap);
    setTxtAny("link-faq",        t.footerLinks.faq);
  }

  // RTL
  document.body.setAttribute("dir", lang === "ar" ? "rtl" : "ltr");
}

// Inicijalizacija
document.addEventListener("DOMContentLoaded", () => {
  const saved  = localStorage.getItem('forecastlerLang');
  const browser = (navigator.language || 'en').slice(0,2);
  const initial = saved || (browser === 'sr' ? 'sr' : 'en');
  setLanguage(initial);
});

// izloži funkcije za druge skripte (meni i sl.)
window.setLanguage = setLanguage;
window.T = function(){ return translations[trenutniJezik] || translations.en; };
